### ISSUE TITLE
.get doesn't consider most-recently-read access

### ISSUE THREAD

**Issue by oleiba** [chriso/lru#16]
Hi, in function `get` I see it calculates whether an element's `modified` field is set in such way that its difference with `Date.now()` is more than `maxAge`, and if so it removes that key and returns `undefined`. 
However, it does not consider the most-recent time where an element was **read**, i.e. was accessed with a previous `get`: the `modified` property is set only inside function `set`.
This is in contrast to the documentation and to general LRU expected behavior AFAIK.

**Comment by chriso** [comment]
@mafintosh do you want to have a look at this since you added `maxAge` in #13?

**Comment by mafintosh** [comment]
This is working as designed. `modified` is only used when using `maxAge`. The entire cache still follows the classic LRU semantics. `maxAge` just allows you to easily add time-based caching on top as well.
