### ISSUE TITLE
Differences/benefits to lru-cache

### ISSUE THREAD

**Issue by kesla** [chriso/lru#21]
Hey,

I've always been using https://github.com/isaacs/node-lru-cache for when I need a in-memory lru cache. But now I found this.

Any reason I should change and use this instead of lru-cache? :)

**Comment by chriso** [comment]
A shorter `require` line? ;)

In all seriousness, it looks like the other library is almost identical. If anything it and has a few more features: forward/backward iteration, etc. Probably no reason to switch :smile:

**Comment by mafintosh** [comment]
Just adding that i originally used this because the api of this made it a bit simpler to construct certain lru datastructures on top of this (access to .head and .tail fx).
