### ISSUE TITLE
Add more control on `maxAge` eviction

### ISSUE THREAD

**Issue by yciabaud** [chriso/lru#23]
Hello,
The rule `maxAge` being checked only on `get` calls is a bit restrictive to me. In my use case. I use `peek` to select some elements and then I really use only some of them and call `get`.

In this way,  I keep the last used date accurate to evict the oldest when `max` is reached.
Now most of my elements are never accessed using `get` and `maxAge` is not triggered.

What do you think about adding a method to check availability or adding a parameter to `get` or `peek` to control `maxAge` eviction?

It would prevent me for doing this:
```javascript
// Check manually if the peer is active
if (peers.maxAge && (Date.now() - peers.cache[peerId].modified) > peers.maxAge) {
  peers.remove(peerId)
  continue
}
// Don't mark the peer as most recently used on announce
var peer = this.peers.peek(peerId)
```
I can propose a PR in this way if you want to.

**Comment by chriso** [comment]
Happy to defer to @mafintosh here since he was the one that added it (#13).

**Comment by DiegoRBaquero** [comment]
Maybe have a checkAge(key) function which can be used internally (for get and peek [if added with parameter condition]) and externally?

**Comment by mafintosh** [comment]
I'm not sure I understand the use-case? Why don't just call get? Get doesn't change any dates. It just evicts the item if its too old (pretends it never existed).

**Comment by mafintosh** [comment]
Actually we should make .peek respect maxAge. It's kind of a bug that it doesn't

**Comment by DiegoRBaquero** [comment]
It might not changed the modified date (only in set method) but it does move it to the head.

**Comment by mafintosh** [comment]
@DiegoRBaquero would this be fixed my making .peek respect maxAge?

**Comment by DiegoRBaquero** [comment]
@mafintosh yeah. Then there would be no need for a checkAge method, as we could just discard the peek result.

**Comment by mafintosh** [comment]
let me just fix that real quick ...

**Comment by mafintosh** [comment]
landed in master

**Comment by mafintosh** [comment]
i'm gonna release this + the .keys thing as a major bump since its technically changing behaivor

**Comment by mafintosh** [comment]
out in 3.0.0, if you still need more maxAge flexibility feel free to re-open this

**Comment by yciabaud** [comment]
Thank you for your reactivity, making peek respect maxAge fixes my issue. 
I was not sure this was not the expected behavior of peek.
