### ISSUE TITLE
backed by external service

### ISSUE THREAD

**Issue by Kikobeats** [chriso/lru#31]
I'm loving this LRU cache implementation, but I need use it out of my main node process.

I'm playing with the idea of move the cache in a redis service, so I want to ask: do you think that could be more or less easy create a memory laye abtraction, using memory as default, but making possible use specific implementation like redis? 😄

**Comment by mafintosh** [comment]
It would change the interface from sync to async so you should prob tinker with a async version seperately

**Comment by Kikobeats** [comment]
I was reading this:
https://github.com/zkat/make-fetch-happen#example-3

And I discovered that exists an [Cache API](https://developer.mozilla.org/en-US/docs/Web/API/Cache).

The point is, this cache interface is oriented for request/response workflow, but the interesting thing is that the implementation use Promise; this make easy write a sync and async version, wrapping the specific implementation inside a promise.

Do you think this could be a good start point?

**Comment by Kikobeats** [comment]
This could be a good approach to be backed by whatever external service:
https://github.com/lukechilds/keyv
